# Numpy

In [1]:
import numpy as np

In [2]:
x = [2, 3, 4, 6]
y = np.array(x)

In [10]:
print(type(x), x)
print(type(y), y)

<class 'list'> [2, 3, 4, 6]
<class 'numpy.ndarray'> [2 3 4 6]


In [11]:
print(x[1:3])

[3, 4]


In [12]:
print(y[1:3])

[3 4]


In [13]:
print(x[[0, 2]])

TypeError: list indices must be integers or slices, not list

In [14]:
print(y[[0, 2]])

[2 4]


In [15]:
print(y[y>3])

[4 6]


In [16]:
print(x * 5)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [17]:
print(y * 5)

[10 15 20 30]


In [18]:
print(x ** 2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
print(y ** 2)

[ 4  9 16 36]


In [20]:
matrix = [[1, 2, 4], [3, 1, 0]]
nd_array = np.array(matrix)

In [22]:
print(matrix[1][2])

0


In [23]:
print(nd_array[1, 2])

0


In [24]:
print(np.random.rand())

0.45938682877985204


In [25]:
print(np.random.randn())

0.1420771684022972


In [26]:
print(np.random.randn(4))

[-1.27422559 -0.66602354  0.78526286  0.17379852]


In [27]:
print(np.random.randn(4, 5))

[[ 0.21881938  0.37813006  0.03817069 -1.72291084 -0.18358738]
 [ 1.38480473  1.27277571  0.92682284 -0.87555849 -0.84346803]
 [ 0.37765189  2.3363688   0.97330338 -2.17262384  0.4254825 ]
 [-0.15884324  1.13248997 -0.58171352  1.40347467  1.06301985]]


In [28]:
print(np.arange(0, 8, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]


In [29]:
print(range(0, 8, 0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [32]:
%timeit np.arange(0, 10000)
%timeit range(0, 10000)

The slowest run took 8.20 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 11.6 µs per loop
The slowest run took 5.01 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 277 ns per loop
